default_chain: stride
chains:
  stride:
    key: icq1
    chain-id: local-test-1
    rpc-addr: http://localhost:26657
    grpc-addr: http://localhost:9090
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 1ustrd
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  gaia:
    key: icq2
    chain-id: cosmoshub-4
    rpc-addr: http://gaia-fleet-direct.frontend.stridenet.co:26657
    grpc-addr: http://gaia-fleet-direct.frontend.stridenet.co:9090
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 1uatom
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
