default_chain: stride
chains:
  stride:
    key: icq1
    chain-id: local-test-1
    rpc-addr: http://localhost:26657
    grpc-addr: http://localhost:9090
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 1ustrd
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  gaia:
    key: icq2
    chain-id: cosmoshub-4
    rpc-addr: https://cosmoshub-4--rpc--full.datahub.figment.io:443/apikey/8dc427b6e0678d0ce615c03137db61a0
    grpc-addr: http://cosmos-grpc.polkachu.com:49090
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 1uatom
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
