name: Gosec
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Run cosmos Gosec Security Scanner
        uses: cosmos/gosec@master
        with:
          args: -exclude-dir=deps -severity=high ./...
