name: staticcheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  golangci:
    name: staticcheck
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Setup Golang
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.18
      - name: staticcheck
        run: make staticcheck